
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=grafdev
      - DATABASE_PASSWORD=grafpass
      - DATABASE_NAME=gooddeeds
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: grafdev
      POSTGRES_PASSWORD: grafpass
      POSTGRES_DB: gooddeeds
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
